---
language: ruby
cache: bundler
rvm:
  - 2.7.2
  - 2.6.6
  - 2.5.8
gemfile:
  - gemfiles/Gemfile.rails_6.1.0
  - gemfiles/Gemfile.rails_6.0.3.4
  - gemfiles/Gemfile.rails_5.2.4
before_install: gem install bundler -v 2.1.4
